FROM node:alpine as build
WORKDIR /app
COPY package.json .
RUN npm install
COPY . .
RUN npm run build

FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY conf/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80

CMD [ "nginx", "-g", "daemon off;" ]

# docker run --name nginx-app -it --rm -p 3000:80 powergeoff/weather-app-ui-nginx
#                                                 powergeoff/weather-app-ui-nginx


