version: "3.8"
services:
  api:
    build:
      context: ./
      dockerfile: API.Dockerfile
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  ui:
    build: ./WeatherApp.UI
    ports:
      - 3000:3000
    env_file:
      - ./WeatherApp.UI/.env
    volumes:
      - ./WeatherApp.UI/src:/app/src
    stdin_open: true
    tty: true
#docker-compose up -d
#deletes all containers and networks but not volumes
#docker-compose down
