# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18.17.1
        uses: actions/setup-node@v2
        with:
          node-version: 18.17.1
      - run: npm install
        working-directory: ./WeatherApp.UI
      - run: npm test --logger "trx;LogFileName=test-results.trx" || true
        working-directory: ./WeatherApp.UI

      - name: Test Report
        uses: dorny/test-reporter@v1

        if: always()
        with:
          name: JEST Tests # Name of the check run which will be created
          path: "**/test-results.trx" # Path to test results
          reporter: jest-junit
          fail-on-error: true
